package com.mhw.example.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserIsmBeanCriteria {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table ism_user
	 *
	 * @mbggenerated
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table ism_user
	 *
	 * @mbggenerated
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table ism_user
	 *
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	public UserIsmBeanCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table ism_user
	 *
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(String value) {
			addCriterion("sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(String value) {
			addCriterion("sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(String value) {
			addCriterion("sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(String value) {
			addCriterion("sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(String value) {
			addCriterion("sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(String value) {
			addCriterion("sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLike(String value) {
			addCriterion("sex like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotLike(String value) {
			addCriterion("sex not like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<String> values) {
			addCriterion("sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<String> values) {
			addCriterion("sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(String value1, String value2) {
			addCriterion("sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(String value1, String value2) {
			addCriterion("sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeIsNull() {
			addCriterion("register_time is null");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeIsNotNull() {
			addCriterion("register_time is not null");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeEqualTo(Date value) {
			addCriterion("register_time =", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeNotEqualTo(Date value) {
			addCriterion("register_time <>", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeGreaterThan(Date value) {
			addCriterion("register_time >", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("register_time >=", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeLessThan(Date value) {
			addCriterion("register_time <", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeLessThanOrEqualTo(Date value) {
			addCriterion("register_time <=", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeIn(List<Date> values) {
			addCriterion("register_time in", values, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeNotIn(List<Date> values) {
			addCriterion("register_time not in", values, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeBetween(Date value1, Date value2) {
			addCriterion("register_time between", value1, value2, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeNotBetween(Date value1, Date value2) {
			addCriterion("register_time not between", value1, value2, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterIpIsNull() {
			addCriterion("register_ip is null");
			return (Criteria) this;
		}

		public Criteria andRegisterIpIsNotNull() {
			addCriterion("register_ip is not null");
			return (Criteria) this;
		}

		public Criteria andRegisterIpEqualTo(String value) {
			addCriterion("register_ip =", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpNotEqualTo(String value) {
			addCriterion("register_ip <>", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpGreaterThan(String value) {
			addCriterion("register_ip >", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpGreaterThanOrEqualTo(String value) {
			addCriterion("register_ip >=", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpLessThan(String value) {
			addCriterion("register_ip <", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpLessThanOrEqualTo(String value) {
			addCriterion("register_ip <=", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpLike(String value) {
			addCriterion("register_ip like", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpNotLike(String value) {
			addCriterion("register_ip not like", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpIn(List<String> values) {
			addCriterion("register_ip in", values, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpNotIn(List<String> values) {
			addCriterion("register_ip not in", values, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpBetween(String value1, String value2) {
			addCriterion("register_ip between", value1, value2, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpNotBetween(String value1, String value2) {
			addCriterion("register_ip not between", value1, value2, "registerIp");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("mobile is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("mobile is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("mobile =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("mobile <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("mobile >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("mobile >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("mobile <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("mobile <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("mobile like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("mobile not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("mobile in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("mobile not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("mobile between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("mobile not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBindIsNull() {
			addCriterion("mobile_bind is null");
			return (Criteria) this;
		}

		public Criteria andMobileBindIsNotNull() {
			addCriterion("mobile_bind is not null");
			return (Criteria) this;
		}

		public Criteria andMobileBindEqualTo(Integer value) {
			addCriterion("mobile_bind =", value, "mobileBind");
			return (Criteria) this;
		}

		public Criteria andMobileBindNotEqualTo(Integer value) {
			addCriterion("mobile_bind <>", value, "mobileBind");
			return (Criteria) this;
		}

		public Criteria andMobileBindGreaterThan(Integer value) {
			addCriterion("mobile_bind >", value, "mobileBind");
			return (Criteria) this;
		}

		public Criteria andMobileBindGreaterThanOrEqualTo(Integer value) {
			addCriterion("mobile_bind >=", value, "mobileBind");
			return (Criteria) this;
		}

		public Criteria andMobileBindLessThan(Integer value) {
			addCriterion("mobile_bind <", value, "mobileBind");
			return (Criteria) this;
		}

		public Criteria andMobileBindLessThanOrEqualTo(Integer value) {
			addCriterion("mobile_bind <=", value, "mobileBind");
			return (Criteria) this;
		}

		public Criteria andMobileBindIn(List<Integer> values) {
			addCriterion("mobile_bind in", values, "mobileBind");
			return (Criteria) this;
		}

		public Criteria andMobileBindNotIn(List<Integer> values) {
			addCriterion("mobile_bind not in", values, "mobileBind");
			return (Criteria) this;
		}

		public Criteria andMobileBindBetween(Integer value1, Integer value2) {
			addCriterion("mobile_bind between", value1, value2, "mobileBind");
			return (Criteria) this;
		}

		public Criteria andMobileBindNotBetween(Integer value1, Integer value2) {
			addCriterion("mobile_bind not between", value1, value2, "mobileBind");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBindIsNull() {
			addCriterion("email_bind is null");
			return (Criteria) this;
		}

		public Criteria andEmailBindIsNotNull() {
			addCriterion("email_bind is not null");
			return (Criteria) this;
		}

		public Criteria andEmailBindEqualTo(Integer value) {
			addCriterion("email_bind =", value, "emailBind");
			return (Criteria) this;
		}

		public Criteria andEmailBindNotEqualTo(Integer value) {
			addCriterion("email_bind <>", value, "emailBind");
			return (Criteria) this;
		}

		public Criteria andEmailBindGreaterThan(Integer value) {
			addCriterion("email_bind >", value, "emailBind");
			return (Criteria) this;
		}

		public Criteria andEmailBindGreaterThanOrEqualTo(Integer value) {
			addCriterion("email_bind >=", value, "emailBind");
			return (Criteria) this;
		}

		public Criteria andEmailBindLessThan(Integer value) {
			addCriterion("email_bind <", value, "emailBind");
			return (Criteria) this;
		}

		public Criteria andEmailBindLessThanOrEqualTo(Integer value) {
			addCriterion("email_bind <=", value, "emailBind");
			return (Criteria) this;
		}

		public Criteria andEmailBindIn(List<Integer> values) {
			addCriterion("email_bind in", values, "emailBind");
			return (Criteria) this;
		}

		public Criteria andEmailBindNotIn(List<Integer> values) {
			addCriterion("email_bind not in", values, "emailBind");
			return (Criteria) this;
		}

		public Criteria andEmailBindBetween(Integer value1, Integer value2) {
			addCriterion("email_bind between", value1, value2, "emailBind");
			return (Criteria) this;
		}

		public Criteria andEmailBindNotBetween(Integer value1, Integer value2) {
			addCriterion("email_bind not between", value1, value2, "emailBind");
			return (Criteria) this;
		}

		public Criteria andNikeNameIsNull() {
			addCriterion("nike_name is null");
			return (Criteria) this;
		}

		public Criteria andNikeNameIsNotNull() {
			addCriterion("nike_name is not null");
			return (Criteria) this;
		}

		public Criteria andNikeNameEqualTo(String value) {
			addCriterion("nike_name =", value, "nikeName");
			return (Criteria) this;
		}

		public Criteria andNikeNameNotEqualTo(String value) {
			addCriterion("nike_name <>", value, "nikeName");
			return (Criteria) this;
		}

		public Criteria andNikeNameGreaterThan(String value) {
			addCriterion("nike_name >", value, "nikeName");
			return (Criteria) this;
		}

		public Criteria andNikeNameGreaterThanOrEqualTo(String value) {
			addCriterion("nike_name >=", value, "nikeName");
			return (Criteria) this;
		}

		public Criteria andNikeNameLessThan(String value) {
			addCriterion("nike_name <", value, "nikeName");
			return (Criteria) this;
		}

		public Criteria andNikeNameLessThanOrEqualTo(String value) {
			addCriterion("nike_name <=", value, "nikeName");
			return (Criteria) this;
		}

		public Criteria andNikeNameLike(String value) {
			addCriterion("nike_name like", value, "nikeName");
			return (Criteria) this;
		}

		public Criteria andNikeNameNotLike(String value) {
			addCriterion("nike_name not like", value, "nikeName");
			return (Criteria) this;
		}

		public Criteria andNikeNameIn(List<String> values) {
			addCriterion("nike_name in", values, "nikeName");
			return (Criteria) this;
		}

		public Criteria andNikeNameNotIn(List<String> values) {
			addCriterion("nike_name not in", values, "nikeName");
			return (Criteria) this;
		}

		public Criteria andNikeNameBetween(String value1, String value2) {
			addCriterion("nike_name between", value1, value2, "nikeName");
			return (Criteria) this;
		}

		public Criteria andNikeNameNotBetween(String value1, String value2) {
			addCriterion("nike_name not between", value1, value2, "nikeName");
			return (Criteria) this;
		}

		public Criteria andHeadimgIsNull() {
			addCriterion("headimg is null");
			return (Criteria) this;
		}

		public Criteria andHeadimgIsNotNull() {
			addCriterion("headimg is not null");
			return (Criteria) this;
		}

		public Criteria andHeadimgEqualTo(String value) {
			addCriterion("headimg =", value, "headimg");
			return (Criteria) this;
		}

		public Criteria andHeadimgNotEqualTo(String value) {
			addCriterion("headimg <>", value, "headimg");
			return (Criteria) this;
		}

		public Criteria andHeadimgGreaterThan(String value) {
			addCriterion("headimg >", value, "headimg");
			return (Criteria) this;
		}

		public Criteria andHeadimgGreaterThanOrEqualTo(String value) {
			addCriterion("headimg >=", value, "headimg");
			return (Criteria) this;
		}

		public Criteria andHeadimgLessThan(String value) {
			addCriterion("headimg <", value, "headimg");
			return (Criteria) this;
		}

		public Criteria andHeadimgLessThanOrEqualTo(String value) {
			addCriterion("headimg <=", value, "headimg");
			return (Criteria) this;
		}

		public Criteria andHeadimgLike(String value) {
			addCriterion("headimg like", value, "headimg");
			return (Criteria) this;
		}

		public Criteria andHeadimgNotLike(String value) {
			addCriterion("headimg not like", value, "headimg");
			return (Criteria) this;
		}

		public Criteria andHeadimgIn(List<String> values) {
			addCriterion("headimg in", values, "headimg");
			return (Criteria) this;
		}

		public Criteria andHeadimgNotIn(List<String> values) {
			addCriterion("headimg not in", values, "headimg");
			return (Criteria) this;
		}

		public Criteria andHeadimgBetween(String value1, String value2) {
			addCriterion("headimg between", value1, value2, "headimg");
			return (Criteria) this;
		}

		public Criteria andHeadimgNotBetween(String value1, String value2) {
			addCriterion("headimg not between", value1, value2, "headimg");
			return (Criteria) this;
		}

		public Criteria andLastloginTimeIsNull() {
			addCriterion("lastlogin_time is null");
			return (Criteria) this;
		}

		public Criteria andLastloginTimeIsNotNull() {
			addCriterion("lastlogin_time is not null");
			return (Criteria) this;
		}

		public Criteria andLastloginTimeEqualTo(Date value) {
			addCriterion("lastlogin_time =", value, "lastloginTime");
			return (Criteria) this;
		}

		public Criteria andLastloginTimeNotEqualTo(Date value) {
			addCriterion("lastlogin_time <>", value, "lastloginTime");
			return (Criteria) this;
		}

		public Criteria andLastloginTimeGreaterThan(Date value) {
			addCriterion("lastlogin_time >", value, "lastloginTime");
			return (Criteria) this;
		}

		public Criteria andLastloginTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("lastlogin_time >=", value, "lastloginTime");
			return (Criteria) this;
		}

		public Criteria andLastloginTimeLessThan(Date value) {
			addCriterion("lastlogin_time <", value, "lastloginTime");
			return (Criteria) this;
		}

		public Criteria andLastloginTimeLessThanOrEqualTo(Date value) {
			addCriterion("lastlogin_time <=", value, "lastloginTime");
			return (Criteria) this;
		}

		public Criteria andLastloginTimeIn(List<Date> values) {
			addCriterion("lastlogin_time in", values, "lastloginTime");
			return (Criteria) this;
		}

		public Criteria andLastloginTimeNotIn(List<Date> values) {
			addCriterion("lastlogin_time not in", values, "lastloginTime");
			return (Criteria) this;
		}

		public Criteria andLastloginTimeBetween(Date value1, Date value2) {
			addCriterion("lastlogin_time between", value1, value2, "lastloginTime");
			return (Criteria) this;
		}

		public Criteria andLastloginTimeNotBetween(Date value1, Date value2) {
			addCriterion("lastlogin_time not between", value1, value2, "lastloginTime");
			return (Criteria) this;
		}

		public Criteria andLastloginIpIsNull() {
			addCriterion("lastlogin_ip is null");
			return (Criteria) this;
		}

		public Criteria andLastloginIpIsNotNull() {
			addCriterion("lastlogin_ip is not null");
			return (Criteria) this;
		}

		public Criteria andLastloginIpEqualTo(String value) {
			addCriterion("lastlogin_ip =", value, "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andLastloginIpNotEqualTo(String value) {
			addCriterion("lastlogin_ip <>", value, "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andLastloginIpGreaterThan(String value) {
			addCriterion("lastlogin_ip >", value, "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andLastloginIpGreaterThanOrEqualTo(String value) {
			addCriterion("lastlogin_ip >=", value, "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andLastloginIpLessThan(String value) {
			addCriterion("lastlogin_ip <", value, "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andLastloginIpLessThanOrEqualTo(String value) {
			addCriterion("lastlogin_ip <=", value, "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andLastloginIpLike(String value) {
			addCriterion("lastlogin_ip like", value, "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andLastloginIpNotLike(String value) {
			addCriterion("lastlogin_ip not like", value, "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andLastloginIpIn(List<String> values) {
			addCriterion("lastlogin_ip in", values, "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andLastloginIpNotIn(List<String> values) {
			addCriterion("lastlogin_ip not in", values, "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andLastloginIpBetween(String value1, String value2) {
			addCriterion("lastlogin_ip between", value1, value2, "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andLastloginIpNotBetween(String value1, String value2) {
			addCriterion("lastlogin_ip not between", value1, value2, "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andIsgadIsNull() {
			addCriterion("isgad is null");
			return (Criteria) this;
		}

		public Criteria andIsgadIsNotNull() {
			addCriterion("isgad is not null");
			return (Criteria) this;
		}

		public Criteria andIsgadEqualTo(Integer value) {
			addCriterion("isgad =", value, "isgad");
			return (Criteria) this;
		}

		public Criteria andIsgadNotEqualTo(Integer value) {
			addCriterion("isgad <>", value, "isgad");
			return (Criteria) this;
		}

		public Criteria andIsgadGreaterThan(Integer value) {
			addCriterion("isgad >", value, "isgad");
			return (Criteria) this;
		}

		public Criteria andIsgadGreaterThanOrEqualTo(Integer value) {
			addCriterion("isgad >=", value, "isgad");
			return (Criteria) this;
		}

		public Criteria andIsgadLessThan(Integer value) {
			addCriterion("isgad <", value, "isgad");
			return (Criteria) this;
		}

		public Criteria andIsgadLessThanOrEqualTo(Integer value) {
			addCriterion("isgad <=", value, "isgad");
			return (Criteria) this;
		}

		public Criteria andIsgadIn(List<Integer> values) {
			addCriterion("isgad in", values, "isgad");
			return (Criteria) this;
		}

		public Criteria andIsgadNotIn(List<Integer> values) {
			addCriterion("isgad not in", values, "isgad");
			return (Criteria) this;
		}

		public Criteria andIsgadBetween(Integer value1, Integer value2) {
			addCriterion("isgad between", value1, value2, "isgad");
			return (Criteria) this;
		}

		public Criteria andIsgadNotBetween(Integer value1, Integer value2) {
			addCriterion("isgad not between", value1, value2, "isgad");
			return (Criteria) this;
		}

		public Criteria andAccuntTypeIsNull() {
			addCriterion("accunt_type is null");
			return (Criteria) this;
		}

		public Criteria andAccuntTypeIsNotNull() {
			addCriterion("accunt_type is not null");
			return (Criteria) this;
		}

		public Criteria andAccuntTypeEqualTo(Integer value) {
			addCriterion("accunt_type =", value, "accuntType");
			return (Criteria) this;
		}

		public Criteria andAccuntTypeNotEqualTo(Integer value) {
			addCriterion("accunt_type <>", value, "accuntType");
			return (Criteria) this;
		}

		public Criteria andAccuntTypeGreaterThan(Integer value) {
			addCriterion("accunt_type >", value, "accuntType");
			return (Criteria) this;
		}

		public Criteria andAccuntTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("accunt_type >=", value, "accuntType");
			return (Criteria) this;
		}

		public Criteria andAccuntTypeLessThan(Integer value) {
			addCriterion("accunt_type <", value, "accuntType");
			return (Criteria) this;
		}

		public Criteria andAccuntTypeLessThanOrEqualTo(Integer value) {
			addCriterion("accunt_type <=", value, "accuntType");
			return (Criteria) this;
		}

		public Criteria andAccuntTypeIn(List<Integer> values) {
			addCriterion("accunt_type in", values, "accuntType");
			return (Criteria) this;
		}

		public Criteria andAccuntTypeNotIn(List<Integer> values) {
			addCriterion("accunt_type not in", values, "accuntType");
			return (Criteria) this;
		}

		public Criteria andAccuntTypeBetween(Integer value1, Integer value2) {
			addCriterion("accunt_type between", value1, value2, "accuntType");
			return (Criteria) this;
		}

		public Criteria andAccuntTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("accunt_type not between", value1, value2, "accuntType");
			return (Criteria) this;
		}

		public Criteria andCreatDateIsNull() {
			addCriterion("creat_date is null");
			return (Criteria) this;
		}

		public Criteria andCreatDateIsNotNull() {
			addCriterion("creat_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreatDateEqualTo(Date value) {
			addCriterion("creat_date =", value, "creatDate");
			return (Criteria) this;
		}

		public Criteria andCreatDateNotEqualTo(Date value) {
			addCriterion("creat_date <>", value, "creatDate");
			return (Criteria) this;
		}

		public Criteria andCreatDateGreaterThan(Date value) {
			addCriterion("creat_date >", value, "creatDate");
			return (Criteria) this;
		}

		public Criteria andCreatDateGreaterThanOrEqualTo(Date value) {
			addCriterion("creat_date >=", value, "creatDate");
			return (Criteria) this;
		}

		public Criteria andCreatDateLessThan(Date value) {
			addCriterion("creat_date <", value, "creatDate");
			return (Criteria) this;
		}

		public Criteria andCreatDateLessThanOrEqualTo(Date value) {
			addCriterion("creat_date <=", value, "creatDate");
			return (Criteria) this;
		}

		public Criteria andCreatDateIn(List<Date> values) {
			addCriterion("creat_date in", values, "creatDate");
			return (Criteria) this;
		}

		public Criteria andCreatDateNotIn(List<Date> values) {
			addCriterion("creat_date not in", values, "creatDate");
			return (Criteria) this;
		}

		public Criteria andCreatDateBetween(Date value1, Date value2) {
			addCriterion("creat_date between", value1, value2, "creatDate");
			return (Criteria) this;
		}

		public Criteria andCreatDateNotBetween(Date value1, Date value2) {
			addCriterion("creat_date not between", value1, value2, "creatDate");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNull() {
			addCriterion("creator is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNotNull() {
			addCriterion("creator is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorEqualTo(String value) {
			addCriterion("creator =", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotEqualTo(String value) {
			addCriterion("creator <>", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThan(String value) {
			addCriterion("creator >", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThanOrEqualTo(String value) {
			addCriterion("creator >=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThan(String value) {
			addCriterion("creator <", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThanOrEqualTo(String value) {
			addCriterion("creator <=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLike(String value) {
			addCriterion("creator like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotLike(String value) {
			addCriterion("creator not like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorIn(List<String> values) {
			addCriterion("creator in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotIn(List<String> values) {
			addCriterion("creator not in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorBetween(String value1, String value2) {
			addCriterion("creator between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotBetween(String value1, String value2) {
			addCriterion("creator not between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andModifyDateIsNull() {
			addCriterion("modify_date is null");
			return (Criteria) this;
		}

		public Criteria andModifyDateIsNotNull() {
			addCriterion("modify_date is not null");
			return (Criteria) this;
		}

		public Criteria andModifyDateEqualTo(Date value) {
			addCriterion("modify_date =", value, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateNotEqualTo(Date value) {
			addCriterion("modify_date <>", value, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateGreaterThan(Date value) {
			addCriterion("modify_date >", value, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
			addCriterion("modify_date >=", value, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateLessThan(Date value) {
			addCriterion("modify_date <", value, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateLessThanOrEqualTo(Date value) {
			addCriterion("modify_date <=", value, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateIn(List<Date> values) {
			addCriterion("modify_date in", values, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateNotIn(List<Date> values) {
			addCriterion("modify_date not in", values, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateBetween(Date value1, Date value2) {
			addCriterion("modify_date between", value1, value2, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateNotBetween(Date value1, Date value2) {
			addCriterion("modify_date not between", value1, value2, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifierIsNull() {
			addCriterion("modifier is null");
			return (Criteria) this;
		}

		public Criteria andModifierIsNotNull() {
			addCriterion("modifier is not null");
			return (Criteria) this;
		}

		public Criteria andModifierEqualTo(String value) {
			addCriterion("modifier =", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotEqualTo(String value) {
			addCriterion("modifier <>", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThan(String value) {
			addCriterion("modifier >", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanOrEqualTo(String value) {
			addCriterion("modifier >=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThan(String value) {
			addCriterion("modifier <", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanOrEqualTo(String value) {
			addCriterion("modifier <=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLike(String value) {
			addCriterion("modifier like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotLike(String value) {
			addCriterion("modifier not like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierIn(List<String> values) {
			addCriterion("modifier in", values, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotIn(List<String> values) {
			addCriterion("modifier not in", values, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierBetween(String value1, String value2) {
			addCriterion("modifier between", value1, value2, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotBetween(String value1, String value2) {
			addCriterion("modifier not between", value1, value2, "modifier");
			return (Criteria) this;
		}

		public Criteria andFansNumIsNull() {
			addCriterion("fans_num is null");
			return (Criteria) this;
		}

		public Criteria andFansNumIsNotNull() {
			addCriterion("fans_num is not null");
			return (Criteria) this;
		}

		public Criteria andFansNumEqualTo(Integer value) {
			addCriterion("fans_num =", value, "fansNum");
			return (Criteria) this;
		}

		public Criteria andFansNumNotEqualTo(Integer value) {
			addCriterion("fans_num <>", value, "fansNum");
			return (Criteria) this;
		}

		public Criteria andFansNumGreaterThan(Integer value) {
			addCriterion("fans_num >", value, "fansNum");
			return (Criteria) this;
		}

		public Criteria andFansNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("fans_num >=", value, "fansNum");
			return (Criteria) this;
		}

		public Criteria andFansNumLessThan(Integer value) {
			addCriterion("fans_num <", value, "fansNum");
			return (Criteria) this;
		}

		public Criteria andFansNumLessThanOrEqualTo(Integer value) {
			addCriterion("fans_num <=", value, "fansNum");
			return (Criteria) this;
		}

		public Criteria andFansNumIn(List<Integer> values) {
			addCriterion("fans_num in", values, "fansNum");
			return (Criteria) this;
		}

		public Criteria andFansNumNotIn(List<Integer> values) {
			addCriterion("fans_num not in", values, "fansNum");
			return (Criteria) this;
		}

		public Criteria andFansNumBetween(Integer value1, Integer value2) {
			addCriterion("fans_num between", value1, value2, "fansNum");
			return (Criteria) this;
		}

		public Criteria andFansNumNotBetween(Integer value1, Integer value2) {
			addCriterion("fans_num not between", value1, value2, "fansNum");
			return (Criteria) this;
		}

		public Criteria andPatNumIsNull() {
			addCriterion("pat_num is null");
			return (Criteria) this;
		}

		public Criteria andPatNumIsNotNull() {
			addCriterion("pat_num is not null");
			return (Criteria) this;
		}

		public Criteria andPatNumEqualTo(Integer value) {
			addCriterion("pat_num =", value, "patNum");
			return (Criteria) this;
		}

		public Criteria andPatNumNotEqualTo(Integer value) {
			addCriterion("pat_num <>", value, "patNum");
			return (Criteria) this;
		}

		public Criteria andPatNumGreaterThan(Integer value) {
			addCriterion("pat_num >", value, "patNum");
			return (Criteria) this;
		}

		public Criteria andPatNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("pat_num >=", value, "patNum");
			return (Criteria) this;
		}

		public Criteria andPatNumLessThan(Integer value) {
			addCriterion("pat_num <", value, "patNum");
			return (Criteria) this;
		}

		public Criteria andPatNumLessThanOrEqualTo(Integer value) {
			addCriterion("pat_num <=", value, "patNum");
			return (Criteria) this;
		}

		public Criteria andPatNumIn(List<Integer> values) {
			addCriterion("pat_num in", values, "patNum");
			return (Criteria) this;
		}

		public Criteria andPatNumNotIn(List<Integer> values) {
			addCriterion("pat_num not in", values, "patNum");
			return (Criteria) this;
		}

		public Criteria andPatNumBetween(Integer value1, Integer value2) {
			addCriterion("pat_num between", value1, value2, "patNum");
			return (Criteria) this;
		}

		public Criteria andPatNumNotBetween(Integer value1, Integer value2) {
			addCriterion("pat_num not between", value1, value2, "patNum");
			return (Criteria) this;
		}

		public Criteria andBlogNumIsNull() {
			addCriterion("blog_num is null");
			return (Criteria) this;
		}

		public Criteria andBlogNumIsNotNull() {
			addCriterion("blog_num is not null");
			return (Criteria) this;
		}

		public Criteria andBlogNumEqualTo(Integer value) {
			addCriterion("blog_num =", value, "blogNum");
			return (Criteria) this;
		}

		public Criteria andBlogNumNotEqualTo(Integer value) {
			addCriterion("blog_num <>", value, "blogNum");
			return (Criteria) this;
		}

		public Criteria andBlogNumGreaterThan(Integer value) {
			addCriterion("blog_num >", value, "blogNum");
			return (Criteria) this;
		}

		public Criteria andBlogNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("blog_num >=", value, "blogNum");
			return (Criteria) this;
		}

		public Criteria andBlogNumLessThan(Integer value) {
			addCriterion("blog_num <", value, "blogNum");
			return (Criteria) this;
		}

		public Criteria andBlogNumLessThanOrEqualTo(Integer value) {
			addCriterion("blog_num <=", value, "blogNum");
			return (Criteria) this;
		}

		public Criteria andBlogNumIn(List<Integer> values) {
			addCriterion("blog_num in", values, "blogNum");
			return (Criteria) this;
		}

		public Criteria andBlogNumNotIn(List<Integer> values) {
			addCriterion("blog_num not in", values, "blogNum");
			return (Criteria) this;
		}

		public Criteria andBlogNumBetween(Integer value1, Integer value2) {
			addCriterion("blog_num between", value1, value2, "blogNum");
			return (Criteria) this;
		}

		public Criteria andBlogNumNotBetween(Integer value1, Integer value2) {
			addCriterion("blog_num not between", value1, value2, "blogNum");
			return (Criteria) this;
		}

		public Criteria andIsrecommendIsNull() {
			addCriterion("isrecommend is null");
			return (Criteria) this;
		}

		public Criteria andIsrecommendIsNotNull() {
			addCriterion("isrecommend is not null");
			return (Criteria) this;
		}

		public Criteria andIsrecommendEqualTo(Integer value) {
			addCriterion("isrecommend =", value, "isrecommend");
			return (Criteria) this;
		}

		public Criteria andIsrecommendNotEqualTo(Integer value) {
			addCriterion("isrecommend <>", value, "isrecommend");
			return (Criteria) this;
		}

		public Criteria andIsrecommendGreaterThan(Integer value) {
			addCriterion("isrecommend >", value, "isrecommend");
			return (Criteria) this;
		}

		public Criteria andIsrecommendGreaterThanOrEqualTo(Integer value) {
			addCriterion("isrecommend >=", value, "isrecommend");
			return (Criteria) this;
		}

		public Criteria andIsrecommendLessThan(Integer value) {
			addCriterion("isrecommend <", value, "isrecommend");
			return (Criteria) this;
		}

		public Criteria andIsrecommendLessThanOrEqualTo(Integer value) {
			addCriterion("isrecommend <=", value, "isrecommend");
			return (Criteria) this;
		}

		public Criteria andIsrecommendIn(List<Integer> values) {
			addCriterion("isrecommend in", values, "isrecommend");
			return (Criteria) this;
		}

		public Criteria andIsrecommendNotIn(List<Integer> values) {
			addCriterion("isrecommend not in", values, "isrecommend");
			return (Criteria) this;
		}

		public Criteria andIsrecommendBetween(Integer value1, Integer value2) {
			addCriterion("isrecommend between", value1, value2, "isrecommend");
			return (Criteria) this;
		}

		public Criteria andIsrecommendNotBetween(Integer value1, Integer value2) {
			addCriterion("isrecommend not between", value1, value2, "isrecommend");
			return (Criteria) this;
		}

		public Criteria andPvNumIsNull() {
			addCriterion("pv_num is null");
			return (Criteria) this;
		}

		public Criteria andPvNumIsNotNull() {
			addCriterion("pv_num is not null");
			return (Criteria) this;
		}

		public Criteria andPvNumEqualTo(Integer value) {
			addCriterion("pv_num =", value, "pvNum");
			return (Criteria) this;
		}

		public Criteria andPvNumNotEqualTo(Integer value) {
			addCriterion("pv_num <>", value, "pvNum");
			return (Criteria) this;
		}

		public Criteria andPvNumGreaterThan(Integer value) {
			addCriterion("pv_num >", value, "pvNum");
			return (Criteria) this;
		}

		public Criteria andPvNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("pv_num >=", value, "pvNum");
			return (Criteria) this;
		}

		public Criteria andPvNumLessThan(Integer value) {
			addCriterion("pv_num <", value, "pvNum");
			return (Criteria) this;
		}

		public Criteria andPvNumLessThanOrEqualTo(Integer value) {
			addCriterion("pv_num <=", value, "pvNum");
			return (Criteria) this;
		}

		public Criteria andPvNumIn(List<Integer> values) {
			addCriterion("pv_num in", values, "pvNum");
			return (Criteria) this;
		}

		public Criteria andPvNumNotIn(List<Integer> values) {
			addCriterion("pv_num not in", values, "pvNum");
			return (Criteria) this;
		}

		public Criteria andPvNumBetween(Integer value1, Integer value2) {
			addCriterion("pv_num between", value1, value2, "pvNum");
			return (Criteria) this;
		}

		public Criteria andPvNumNotBetween(Integer value1, Integer value2) {
			addCriterion("pv_num not between", value1, value2, "pvNum");
			return (Criteria) this;
		}

		public Criteria andWeightIsNull() {
			addCriterion("weight is null");
			return (Criteria) this;
		}

		public Criteria andWeightIsNotNull() {
			addCriterion("weight is not null");
			return (Criteria) this;
		}

		public Criteria andWeightEqualTo(Integer value) {
			addCriterion("weight =", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotEqualTo(Integer value) {
			addCriterion("weight <>", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThan(Integer value) {
			addCriterion("weight >", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("weight >=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThan(Integer value) {
			addCriterion("weight <", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThanOrEqualTo(Integer value) {
			addCriterion("weight <=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightIn(List<Integer> values) {
			addCriterion("weight in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotIn(List<Integer> values) {
			addCriterion("weight not in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightBetween(Integer value1, Integer value2) {
			addCriterion("weight between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotBetween(Integer value1, Integer value2) {
			addCriterion("weight not between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdIsNull() {
			addCriterion("call_history_prod is null");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdIsNotNull() {
			addCriterion("call_history_prod is not null");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdEqualTo(String value) {
			addCriterion("call_history_prod =", value, "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdNotEqualTo(String value) {
			addCriterion("call_history_prod <>", value, "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdGreaterThan(String value) {
			addCriterion("call_history_prod >", value, "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdGreaterThanOrEqualTo(String value) {
			addCriterion("call_history_prod >=", value, "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdLessThan(String value) {
			addCriterion("call_history_prod <", value, "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdLessThanOrEqualTo(String value) {
			addCriterion("call_history_prod <=", value, "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdLike(String value) {
			addCriterion("call_history_prod like", value, "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdNotLike(String value) {
			addCriterion("call_history_prod not like", value, "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdIn(List<String> values) {
			addCriterion("call_history_prod in", values, "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdNotIn(List<String> values) {
			addCriterion("call_history_prod not in", values, "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdBetween(String value1, String value2) {
			addCriterion("call_history_prod between", value1, value2, "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdNotBetween(String value1, String value2) {
			addCriterion("call_history_prod not between", value1, value2, "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManIsNull() {
			addCriterion("call_history_man is null");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManIsNotNull() {
			addCriterion("call_history_man is not null");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManEqualTo(String value) {
			addCriterion("call_history_man =", value, "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManNotEqualTo(String value) {
			addCriterion("call_history_man <>", value, "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManGreaterThan(String value) {
			addCriterion("call_history_man >", value, "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManGreaterThanOrEqualTo(String value) {
			addCriterion("call_history_man >=", value, "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManLessThan(String value) {
			addCriterion("call_history_man <", value, "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManLessThanOrEqualTo(String value) {
			addCriterion("call_history_man <=", value, "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManLike(String value) {
			addCriterion("call_history_man like", value, "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManNotLike(String value) {
			addCriterion("call_history_man not like", value, "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManIn(List<String> values) {
			addCriterion("call_history_man in", values, "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManNotIn(List<String> values) {
			addCriterion("call_history_man not in", values, "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManBetween(String value1, String value2) {
			addCriterion("call_history_man between", value1, value2, "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManNotBetween(String value1, String value2) {
			addCriterion("call_history_man not between", value1, value2, "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileIsNull() {
			addCriterion("personal_simple_profile is null");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileIsNotNull() {
			addCriterion("personal_simple_profile is not null");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileEqualTo(String value) {
			addCriterion("personal_simple_profile =", value, "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileNotEqualTo(String value) {
			addCriterion("personal_simple_profile <>", value, "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileGreaterThan(String value) {
			addCriterion("personal_simple_profile >", value, "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileGreaterThanOrEqualTo(String value) {
			addCriterion("personal_simple_profile >=", value, "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileLessThan(String value) {
			addCriterion("personal_simple_profile <", value, "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileLessThanOrEqualTo(String value) {
			addCriterion("personal_simple_profile <=", value, "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileLike(String value) {
			addCriterion("personal_simple_profile like", value, "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileNotLike(String value) {
			addCriterion("personal_simple_profile not like", value, "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileIn(List<String> values) {
			addCriterion("personal_simple_profile in", values, "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileNotIn(List<String> values) {
			addCriterion("personal_simple_profile not in", values, "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileBetween(String value1, String value2) {
			addCriterion("personal_simple_profile between", value1, value2, "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileNotBetween(String value1, String value2) {
			addCriterion("personal_simple_profile not between", value1, value2, "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andPwdLevelIsNull() {
			addCriterion("pwd_level is null");
			return (Criteria) this;
		}

		public Criteria andPwdLevelIsNotNull() {
			addCriterion("pwd_level is not null");
			return (Criteria) this;
		}

		public Criteria andPwdLevelEqualTo(Integer value) {
			addCriterion("pwd_level =", value, "pwdLevel");
			return (Criteria) this;
		}

		public Criteria andPwdLevelNotEqualTo(Integer value) {
			addCriterion("pwd_level <>", value, "pwdLevel");
			return (Criteria) this;
		}

		public Criteria andPwdLevelGreaterThan(Integer value) {
			addCriterion("pwd_level >", value, "pwdLevel");
			return (Criteria) this;
		}

		public Criteria andPwdLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("pwd_level >=", value, "pwdLevel");
			return (Criteria) this;
		}

		public Criteria andPwdLevelLessThan(Integer value) {
			addCriterion("pwd_level <", value, "pwdLevel");
			return (Criteria) this;
		}

		public Criteria andPwdLevelLessThanOrEqualTo(Integer value) {
			addCriterion("pwd_level <=", value, "pwdLevel");
			return (Criteria) this;
		}

		public Criteria andPwdLevelIn(List<Integer> values) {
			addCriterion("pwd_level in", values, "pwdLevel");
			return (Criteria) this;
		}

		public Criteria andPwdLevelNotIn(List<Integer> values) {
			addCriterion("pwd_level not in", values, "pwdLevel");
			return (Criteria) this;
		}

		public Criteria andPwdLevelBetween(Integer value1, Integer value2) {
			addCriterion("pwd_level between", value1, value2, "pwdLevel");
			return (Criteria) this;
		}

		public Criteria andPwdLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("pwd_level not between", value1, value2, "pwdLevel");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallIsNull() {
			addCriterion("heading_small is null");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallIsNotNull() {
			addCriterion("heading_small is not null");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallEqualTo(String value) {
			addCriterion("heading_small =", value, "headingSmall");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallNotEqualTo(String value) {
			addCriterion("heading_small <>", value, "headingSmall");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallGreaterThan(String value) {
			addCriterion("heading_small >", value, "headingSmall");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallGreaterThanOrEqualTo(String value) {
			addCriterion("heading_small >=", value, "headingSmall");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallLessThan(String value) {
			addCriterion("heading_small <", value, "headingSmall");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallLessThanOrEqualTo(String value) {
			addCriterion("heading_small <=", value, "headingSmall");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallLike(String value) {
			addCriterion("heading_small like", value, "headingSmall");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallNotLike(String value) {
			addCriterion("heading_small not like", value, "headingSmall");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallIn(List<String> values) {
			addCriterion("heading_small in", values, "headingSmall");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallNotIn(List<String> values) {
			addCriterion("heading_small not in", values, "headingSmall");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallBetween(String value1, String value2) {
			addCriterion("heading_small between", value1, value2, "headingSmall");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallNotBetween(String value1, String value2) {
			addCriterion("heading_small not between", value1, value2, "headingSmall");
			return (Criteria) this;
		}

		public Criteria andTagsIsNull() {
			addCriterion("tags is null");
			return (Criteria) this;
		}

		public Criteria andTagsIsNotNull() {
			addCriterion("tags is not null");
			return (Criteria) this;
		}

		public Criteria andTagsEqualTo(String value) {
			addCriterion("tags =", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsNotEqualTo(String value) {
			addCriterion("tags <>", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsGreaterThan(String value) {
			addCriterion("tags >", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsGreaterThanOrEqualTo(String value) {
			addCriterion("tags >=", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsLessThan(String value) {
			addCriterion("tags <", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsLessThanOrEqualTo(String value) {
			addCriterion("tags <=", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsLike(String value) {
			addCriterion("tags like", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsNotLike(String value) {
			addCriterion("tags not like", value, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsIn(List<String> values) {
			addCriterion("tags in", values, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsNotIn(List<String> values) {
			addCriterion("tags not in", values, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsBetween(String value1, String value2) {
			addCriterion("tags between", value1, value2, "tags");
			return (Criteria) this;
		}

		public Criteria andTagsNotBetween(String value1, String value2) {
			addCriterion("tags not between", value1, value2, "tags");
			return (Criteria) this;
		}

		public Criteria andActiveNumIsNull() {
			addCriterion("active_num is null");
			return (Criteria) this;
		}

		public Criteria andActiveNumIsNotNull() {
			addCriterion("active_num is not null");
			return (Criteria) this;
		}

		public Criteria andActiveNumEqualTo(Integer value) {
			addCriterion("active_num =", value, "activeNum");
			return (Criteria) this;
		}

		public Criteria andActiveNumNotEqualTo(Integer value) {
			addCriterion("active_num <>", value, "activeNum");
			return (Criteria) this;
		}

		public Criteria andActiveNumGreaterThan(Integer value) {
			addCriterion("active_num >", value, "activeNum");
			return (Criteria) this;
		}

		public Criteria andActiveNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("active_num >=", value, "activeNum");
			return (Criteria) this;
		}

		public Criteria andActiveNumLessThan(Integer value) {
			addCriterion("active_num <", value, "activeNum");
			return (Criteria) this;
		}

		public Criteria andActiveNumLessThanOrEqualTo(Integer value) {
			addCriterion("active_num <=", value, "activeNum");
			return (Criteria) this;
		}

		public Criteria andActiveNumIn(List<Integer> values) {
			addCriterion("active_num in", values, "activeNum");
			return (Criteria) this;
		}

		public Criteria andActiveNumNotIn(List<Integer> values) {
			addCriterion("active_num not in", values, "activeNum");
			return (Criteria) this;
		}

		public Criteria andActiveNumBetween(Integer value1, Integer value2) {
			addCriterion("active_num between", value1, value2, "activeNum");
			return (Criteria) this;
		}

		public Criteria andActiveNumNotBetween(Integer value1, Integer value2) {
			addCriterion("active_num not between", value1, value2, "activeNum");
			return (Criteria) this;
		}

		public Criteria andLivenessIsNull() {
			addCriterion("liveness is null");
			return (Criteria) this;
		}

		public Criteria andLivenessIsNotNull() {
			addCriterion("liveness is not null");
			return (Criteria) this;
		}

		public Criteria andLivenessEqualTo(Integer value) {
			addCriterion("liveness =", value, "liveness");
			return (Criteria) this;
		}

		public Criteria andLivenessNotEqualTo(Integer value) {
			addCriterion("liveness <>", value, "liveness");
			return (Criteria) this;
		}

		public Criteria andLivenessGreaterThan(Integer value) {
			addCriterion("liveness >", value, "liveness");
			return (Criteria) this;
		}

		public Criteria andLivenessGreaterThanOrEqualTo(Integer value) {
			addCriterion("liveness >=", value, "liveness");
			return (Criteria) this;
		}

		public Criteria andLivenessLessThan(Integer value) {
			addCriterion("liveness <", value, "liveness");
			return (Criteria) this;
		}

		public Criteria andLivenessLessThanOrEqualTo(Integer value) {
			addCriterion("liveness <=", value, "liveness");
			return (Criteria) this;
		}

		public Criteria andLivenessIn(List<Integer> values) {
			addCriterion("liveness in", values, "liveness");
			return (Criteria) this;
		}

		public Criteria andLivenessNotIn(List<Integer> values) {
			addCriterion("liveness not in", values, "liveness");
			return (Criteria) this;
		}

		public Criteria andLivenessBetween(Integer value1, Integer value2) {
			addCriterion("liveness between", value1, value2, "liveness");
			return (Criteria) this;
		}

		public Criteria andLivenessNotBetween(Integer value1, Integer value2) {
			addCriterion("liveness not between", value1, value2, "liveness");
			return (Criteria) this;
		}

		public Criteria andLivenessInitIsNull() {
			addCriterion("liveness_init is null");
			return (Criteria) this;
		}

		public Criteria andLivenessInitIsNotNull() {
			addCriterion("liveness_init is not null");
			return (Criteria) this;
		}

		public Criteria andLivenessInitEqualTo(Integer value) {
			addCriterion("liveness_init =", value, "livenessInit");
			return (Criteria) this;
		}

		public Criteria andLivenessInitNotEqualTo(Integer value) {
			addCriterion("liveness_init <>", value, "livenessInit");
			return (Criteria) this;
		}

		public Criteria andLivenessInitGreaterThan(Integer value) {
			addCriterion("liveness_init >", value, "livenessInit");
			return (Criteria) this;
		}

		public Criteria andLivenessInitGreaterThanOrEqualTo(Integer value) {
			addCriterion("liveness_init >=", value, "livenessInit");
			return (Criteria) this;
		}

		public Criteria andLivenessInitLessThan(Integer value) {
			addCriterion("liveness_init <", value, "livenessInit");
			return (Criteria) this;
		}

		public Criteria andLivenessInitLessThanOrEqualTo(Integer value) {
			addCriterion("liveness_init <=", value, "livenessInit");
			return (Criteria) this;
		}

		public Criteria andLivenessInitIn(List<Integer> values) {
			addCriterion("liveness_init in", values, "livenessInit");
			return (Criteria) this;
		}

		public Criteria andLivenessInitNotIn(List<Integer> values) {
			addCriterion("liveness_init not in", values, "livenessInit");
			return (Criteria) this;
		}

		public Criteria andLivenessInitBetween(Integer value1, Integer value2) {
			addCriterion("liveness_init between", value1, value2, "livenessInit");
			return (Criteria) this;
		}

		public Criteria andLivenessInitNotBetween(Integer value1, Integer value2) {
			addCriterion("liveness_init not between", value1, value2, "livenessInit");
			return (Criteria) this;
		}

		public Criteria andPvLastTimeIsNull() {
			addCriterion("pv_last_time is null");
			return (Criteria) this;
		}

		public Criteria andPvLastTimeIsNotNull() {
			addCriterion("pv_last_time is not null");
			return (Criteria) this;
		}

		public Criteria andPvLastTimeEqualTo(Date value) {
			addCriterion("pv_last_time =", value, "pvLastTime");
			return (Criteria) this;
		}

		public Criteria andPvLastTimeNotEqualTo(Date value) {
			addCriterion("pv_last_time <>", value, "pvLastTime");
			return (Criteria) this;
		}

		public Criteria andPvLastTimeGreaterThan(Date value) {
			addCriterion("pv_last_time >", value, "pvLastTime");
			return (Criteria) this;
		}

		public Criteria andPvLastTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("pv_last_time >=", value, "pvLastTime");
			return (Criteria) this;
		}

		public Criteria andPvLastTimeLessThan(Date value) {
			addCriterion("pv_last_time <", value, "pvLastTime");
			return (Criteria) this;
		}

		public Criteria andPvLastTimeLessThanOrEqualTo(Date value) {
			addCriterion("pv_last_time <=", value, "pvLastTime");
			return (Criteria) this;
		}

		public Criteria andPvLastTimeIn(List<Date> values) {
			addCriterion("pv_last_time in", values, "pvLastTime");
			return (Criteria) this;
		}

		public Criteria andPvLastTimeNotIn(List<Date> values) {
			addCriterion("pv_last_time not in", values, "pvLastTime");
			return (Criteria) this;
		}

		public Criteria andPvLastTimeBetween(Date value1, Date value2) {
			addCriterion("pv_last_time between", value1, value2, "pvLastTime");
			return (Criteria) this;
		}

		public Criteria andPvLastTimeNotBetween(Date value1, Date value2) {
			addCriterion("pv_last_time not between", value1, value2, "pvLastTime");
			return (Criteria) this;
		}

		public Criteria andIspmcompanyIsNull() {
			addCriterion("ispmcompany is null");
			return (Criteria) this;
		}

		public Criteria andIspmcompanyIsNotNull() {
			addCriterion("ispmcompany is not null");
			return (Criteria) this;
		}

		public Criteria andIspmcompanyEqualTo(Integer value) {
			addCriterion("ispmcompany =", value, "ispmcompany");
			return (Criteria) this;
		}

		public Criteria andIspmcompanyNotEqualTo(Integer value) {
			addCriterion("ispmcompany <>", value, "ispmcompany");
			return (Criteria) this;
		}

		public Criteria andIspmcompanyGreaterThan(Integer value) {
			addCriterion("ispmcompany >", value, "ispmcompany");
			return (Criteria) this;
		}

		public Criteria andIspmcompanyGreaterThanOrEqualTo(Integer value) {
			addCriterion("ispmcompany >=", value, "ispmcompany");
			return (Criteria) this;
		}

		public Criteria andIspmcompanyLessThan(Integer value) {
			addCriterion("ispmcompany <", value, "ispmcompany");
			return (Criteria) this;
		}

		public Criteria andIspmcompanyLessThanOrEqualTo(Integer value) {
			addCriterion("ispmcompany <=", value, "ispmcompany");
			return (Criteria) this;
		}

		public Criteria andIspmcompanyIn(List<Integer> values) {
			addCriterion("ispmcompany in", values, "ispmcompany");
			return (Criteria) this;
		}

		public Criteria andIspmcompanyNotIn(List<Integer> values) {
			addCriterion("ispmcompany not in", values, "ispmcompany");
			return (Criteria) this;
		}

		public Criteria andIspmcompanyBetween(Integer value1, Integer value2) {
			addCriterion("ispmcompany between", value1, value2, "ispmcompany");
			return (Criteria) this;
		}

		public Criteria andIspmcompanyNotBetween(Integer value1, Integer value2) {
			addCriterion("ispmcompany not between", value1, value2, "ispmcompany");
			return (Criteria) this;
		}

		public Criteria andHotWeightIsNull() {
			addCriterion("hot_weight is null");
			return (Criteria) this;
		}

		public Criteria andHotWeightIsNotNull() {
			addCriterion("hot_weight is not null");
			return (Criteria) this;
		}

		public Criteria andHotWeightEqualTo(Integer value) {
			addCriterion("hot_weight =", value, "hotWeight");
			return (Criteria) this;
		}

		public Criteria andHotWeightNotEqualTo(Integer value) {
			addCriterion("hot_weight <>", value, "hotWeight");
			return (Criteria) this;
		}

		public Criteria andHotWeightGreaterThan(Integer value) {
			addCriterion("hot_weight >", value, "hotWeight");
			return (Criteria) this;
		}

		public Criteria andHotWeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("hot_weight >=", value, "hotWeight");
			return (Criteria) this;
		}

		public Criteria andHotWeightLessThan(Integer value) {
			addCriterion("hot_weight <", value, "hotWeight");
			return (Criteria) this;
		}

		public Criteria andHotWeightLessThanOrEqualTo(Integer value) {
			addCriterion("hot_weight <=", value, "hotWeight");
			return (Criteria) this;
		}

		public Criteria andHotWeightIn(List<Integer> values) {
			addCriterion("hot_weight in", values, "hotWeight");
			return (Criteria) this;
		}

		public Criteria andHotWeightNotIn(List<Integer> values) {
			addCriterion("hot_weight not in", values, "hotWeight");
			return (Criteria) this;
		}

		public Criteria andHotWeightBetween(Integer value1, Integer value2) {
			addCriterion("hot_weight between", value1, value2, "hotWeight");
			return (Criteria) this;
		}

		public Criteria andHotWeightNotBetween(Integer value1, Integer value2) {
			addCriterion("hot_weight not between", value1, value2, "hotWeight");
			return (Criteria) this;
		}

		public Criteria andIsinterestIsNull() {
			addCriterion("isinterest is null");
			return (Criteria) this;
		}

		public Criteria andIsinterestIsNotNull() {
			addCriterion("isinterest is not null");
			return (Criteria) this;
		}

		public Criteria andIsinterestEqualTo(Integer value) {
			addCriterion("isinterest =", value, "isinterest");
			return (Criteria) this;
		}

		public Criteria andIsinterestNotEqualTo(Integer value) {
			addCriterion("isinterest <>", value, "isinterest");
			return (Criteria) this;
		}

		public Criteria andIsinterestGreaterThan(Integer value) {
			addCriterion("isinterest >", value, "isinterest");
			return (Criteria) this;
		}

		public Criteria andIsinterestGreaterThanOrEqualTo(Integer value) {
			addCriterion("isinterest >=", value, "isinterest");
			return (Criteria) this;
		}

		public Criteria andIsinterestLessThan(Integer value) {
			addCriterion("isinterest <", value, "isinterest");
			return (Criteria) this;
		}

		public Criteria andIsinterestLessThanOrEqualTo(Integer value) {
			addCriterion("isinterest <=", value, "isinterest");
			return (Criteria) this;
		}

		public Criteria andIsinterestIn(List<Integer> values) {
			addCriterion("isinterest in", values, "isinterest");
			return (Criteria) this;
		}

		public Criteria andIsinterestNotIn(List<Integer> values) {
			addCriterion("isinterest not in", values, "isinterest");
			return (Criteria) this;
		}

		public Criteria andIsinterestBetween(Integer value1, Integer value2) {
			addCriterion("isinterest between", value1, value2, "isinterest");
			return (Criteria) this;
		}

		public Criteria andIsinterestNotBetween(Integer value1, Integer value2) {
			addCriterion("isinterest not between", value1, value2, "isinterest");
			return (Criteria) this;
		}

		public Criteria andIsguideIsNull() {
			addCriterion("isguide is null");
			return (Criteria) this;
		}

		public Criteria andIsguideIsNotNull() {
			addCriterion("isguide is not null");
			return (Criteria) this;
		}

		public Criteria andIsguideEqualTo(Integer value) {
			addCriterion("isguide =", value, "isguide");
			return (Criteria) this;
		}

		public Criteria andIsguideNotEqualTo(Integer value) {
			addCriterion("isguide <>", value, "isguide");
			return (Criteria) this;
		}

		public Criteria andIsguideGreaterThan(Integer value) {
			addCriterion("isguide >", value, "isguide");
			return (Criteria) this;
		}

		public Criteria andIsguideGreaterThanOrEqualTo(Integer value) {
			addCriterion("isguide >=", value, "isguide");
			return (Criteria) this;
		}

		public Criteria andIsguideLessThan(Integer value) {
			addCriterion("isguide <", value, "isguide");
			return (Criteria) this;
		}

		public Criteria andIsguideLessThanOrEqualTo(Integer value) {
			addCriterion("isguide <=", value, "isguide");
			return (Criteria) this;
		}

		public Criteria andIsguideIn(List<Integer> values) {
			addCriterion("isguide in", values, "isguide");
			return (Criteria) this;
		}

		public Criteria andIsguideNotIn(List<Integer> values) {
			addCriterion("isguide not in", values, "isguide");
			return (Criteria) this;
		}

		public Criteria andIsguideBetween(Integer value1, Integer value2) {
			addCriterion("isguide between", value1, value2, "isguide");
			return (Criteria) this;
		}

		public Criteria andIsguideNotBetween(Integer value1, Integer value2) {
			addCriterion("isguide not between", value1, value2, "isguide");
			return (Criteria) this;
		}

		public Criteria andScoreResultIsNull() {
			addCriterion("score_result is null");
			return (Criteria) this;
		}

		public Criteria andScoreResultIsNotNull() {
			addCriterion("score_result is not null");
			return (Criteria) this;
		}

		public Criteria andScoreResultEqualTo(Integer value) {
			addCriterion("score_result =", value, "scoreResult");
			return (Criteria) this;
		}

		public Criteria andScoreResultNotEqualTo(Integer value) {
			addCriterion("score_result <>", value, "scoreResult");
			return (Criteria) this;
		}

		public Criteria andScoreResultGreaterThan(Integer value) {
			addCriterion("score_result >", value, "scoreResult");
			return (Criteria) this;
		}

		public Criteria andScoreResultGreaterThanOrEqualTo(Integer value) {
			addCriterion("score_result >=", value, "scoreResult");
			return (Criteria) this;
		}

		public Criteria andScoreResultLessThan(Integer value) {
			addCriterion("score_result <", value, "scoreResult");
			return (Criteria) this;
		}

		public Criteria andScoreResultLessThanOrEqualTo(Integer value) {
			addCriterion("score_result <=", value, "scoreResult");
			return (Criteria) this;
		}

		public Criteria andScoreResultIn(List<Integer> values) {
			addCriterion("score_result in", values, "scoreResult");
			return (Criteria) this;
		}

		public Criteria andScoreResultNotIn(List<Integer> values) {
			addCriterion("score_result not in", values, "scoreResult");
			return (Criteria) this;
		}

		public Criteria andScoreResultBetween(Integer value1, Integer value2) {
			addCriterion("score_result between", value1, value2, "scoreResult");
			return (Criteria) this;
		}

		public Criteria andScoreResultNotBetween(Integer value1, Integer value2) {
			addCriterion("score_result not between", value1, value2, "scoreResult");
			return (Criteria) this;
		}

		public Criteria andIsfundguideIsNull() {
			addCriterion("isfundguide is null");
			return (Criteria) this;
		}

		public Criteria andIsfundguideIsNotNull() {
			addCriterion("isfundguide is not null");
			return (Criteria) this;
		}

		public Criteria andIsfundguideEqualTo(Integer value) {
			addCriterion("isfundguide =", value, "isfundguide");
			return (Criteria) this;
		}

		public Criteria andIsfundguideNotEqualTo(Integer value) {
			addCriterion("isfundguide <>", value, "isfundguide");
			return (Criteria) this;
		}

		public Criteria andIsfundguideGreaterThan(Integer value) {
			addCriterion("isfundguide >", value, "isfundguide");
			return (Criteria) this;
		}

		public Criteria andIsfundguideGreaterThanOrEqualTo(Integer value) {
			addCriterion("isfundguide >=", value, "isfundguide");
			return (Criteria) this;
		}

		public Criteria andIsfundguideLessThan(Integer value) {
			addCriterion("isfundguide <", value, "isfundguide");
			return (Criteria) this;
		}

		public Criteria andIsfundguideLessThanOrEqualTo(Integer value) {
			addCriterion("isfundguide <=", value, "isfundguide");
			return (Criteria) this;
		}

		public Criteria andIsfundguideIn(List<Integer> values) {
			addCriterion("isfundguide in", values, "isfundguide");
			return (Criteria) this;
		}

		public Criteria andIsfundguideNotIn(List<Integer> values) {
			addCriterion("isfundguide not in", values, "isfundguide");
			return (Criteria) this;
		}

		public Criteria andIsfundguideBetween(Integer value1, Integer value2) {
			addCriterion("isfundguide between", value1, value2, "isfundguide");
			return (Criteria) this;
		}

		public Criteria andIsfundguideNotBetween(Integer value1, Integer value2) {
			addCriterion("isfundguide not between", value1, value2, "isfundguide");
			return (Criteria) this;
		}

		public Criteria andControllerSwitchIsNull() {
			addCriterion("controller_switch is null");
			return (Criteria) this;
		}

		public Criteria andControllerSwitchIsNotNull() {
			addCriterion("controller_switch is not null");
			return (Criteria) this;
		}

		public Criteria andControllerSwitchEqualTo(Integer value) {
			addCriterion("controller_switch =", value, "controllerSwitch");
			return (Criteria) this;
		}

		public Criteria andControllerSwitchNotEqualTo(Integer value) {
			addCriterion("controller_switch <>", value, "controllerSwitch");
			return (Criteria) this;
		}

		public Criteria andControllerSwitchGreaterThan(Integer value) {
			addCriterion("controller_switch >", value, "controllerSwitch");
			return (Criteria) this;
		}

		public Criteria andControllerSwitchGreaterThanOrEqualTo(Integer value) {
			addCriterion("controller_switch >=", value, "controllerSwitch");
			return (Criteria) this;
		}

		public Criteria andControllerSwitchLessThan(Integer value) {
			addCriterion("controller_switch <", value, "controllerSwitch");
			return (Criteria) this;
		}

		public Criteria andControllerSwitchLessThanOrEqualTo(Integer value) {
			addCriterion("controller_switch <=", value, "controllerSwitch");
			return (Criteria) this;
		}

		public Criteria andControllerSwitchIn(List<Integer> values) {
			addCriterion("controller_switch in", values, "controllerSwitch");
			return (Criteria) this;
		}

		public Criteria andControllerSwitchNotIn(List<Integer> values) {
			addCriterion("controller_switch not in", values, "controllerSwitch");
			return (Criteria) this;
		}

		public Criteria andControllerSwitchBetween(Integer value1, Integer value2) {
			addCriterion("controller_switch between", value1, value2, "controllerSwitch");
			return (Criteria) this;
		}

		public Criteria andControllerSwitchNotBetween(Integer value1, Integer value2) {
			addCriterion("controller_switch not between", value1, value2, "controllerSwitch");
			return (Criteria) this;
		}

		public Criteria andUserIdLikeInsensitive(String value) {
			addCriterion("upper(user_id) like", value.toUpperCase(), "userId");
			return (Criteria) this;
		}

		public Criteria andUserNameLikeInsensitive(String value) {
			addCriterion("upper(user_name) like", value.toUpperCase(), "userName");
			return (Criteria) this;
		}

		public Criteria andPasswordLikeInsensitive(String value) {
			addCriterion("upper(password) like", value.toUpperCase(), "password");
			return (Criteria) this;
		}

		public Criteria andSexLikeInsensitive(String value) {
			addCriterion("upper(sex) like", value.toUpperCase(), "sex");
			return (Criteria) this;
		}

		public Criteria andRegisterIpLikeInsensitive(String value) {
			addCriterion("upper(register_ip) like", value.toUpperCase(), "registerIp");
			return (Criteria) this;
		}

		public Criteria andMobileLikeInsensitive(String value) {
			addCriterion("upper(mobile) like", value.toUpperCase(), "mobile");
			return (Criteria) this;
		}

		public Criteria andEmailLikeInsensitive(String value) {
			addCriterion("upper(email) like", value.toUpperCase(), "email");
			return (Criteria) this;
		}

		public Criteria andNikeNameLikeInsensitive(String value) {
			addCriterion("upper(nike_name) like", value.toUpperCase(), "nikeName");
			return (Criteria) this;
		}

		public Criteria andHeadimgLikeInsensitive(String value) {
			addCriterion("upper(headimg) like", value.toUpperCase(), "headimg");
			return (Criteria) this;
		}

		public Criteria andLastloginIpLikeInsensitive(String value) {
			addCriterion("upper(lastlogin_ip) like", value.toUpperCase(), "lastloginIp");
			return (Criteria) this;
		}

		public Criteria andAddressLikeInsensitive(String value) {
			addCriterion("upper(address) like", value.toUpperCase(), "address");
			return (Criteria) this;
		}

		public Criteria andCreatorLikeInsensitive(String value) {
			addCriterion("upper(creator) like", value.toUpperCase(), "creator");
			return (Criteria) this;
		}

		public Criteria andModifierLikeInsensitive(String value) {
			addCriterion("upper(modifier) like", value.toUpperCase(), "modifier");
			return (Criteria) this;
		}

		public Criteria andCallHistoryProdLikeInsensitive(String value) {
			addCriterion("upper(call_history_prod) like", value.toUpperCase(), "callHistoryProd");
			return (Criteria) this;
		}

		public Criteria andCallHistoryManLikeInsensitive(String value) {
			addCriterion("upper(call_history_man) like", value.toUpperCase(), "callHistoryMan");
			return (Criteria) this;
		}

		public Criteria andPersonalSimpleProfileLikeInsensitive(String value) {
			addCriterion("upper(personal_simple_profile) like", value.toUpperCase(), "personalSimpleProfile");
			return (Criteria) this;
		}

		public Criteria andHeadingSmallLikeInsensitive(String value) {
			addCriterion("upper(heading_small) like", value.toUpperCase(), "headingSmall");
			return (Criteria) this;
		}

		public Criteria andTagsLikeInsensitive(String value) {
			addCriterion("upper(tags) like", value.toUpperCase(), "tags");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table ism_user
	 *
	 * @mbggenerated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table ism_user
	 *
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}
