package com.mhw.example.model;

import java.io.Serializable;
import java.util.Date;

public class UserIsmBean implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.user_id
	 *
	 * @mbggenerated
	 */
	private String userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.user_name
	 *
	 * @mbggenerated
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.password
	 *
	 * @mbggenerated
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.sex
	 *
	 * @mbggenerated
	 */
	private String sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.register_time
	 *
	 * @mbggenerated
	 */
	private Date registerTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.register_ip
	 *
	 * @mbggenerated
	 */
	private String registerIp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.mobile
	 *
	 * @mbggenerated
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.mobile_bind
	 *
	 * @mbggenerated
	 */
	private Integer mobileBind;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.email
	 *
	 * @mbggenerated
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.email_bind
	 *
	 * @mbggenerated
	 */
	private Integer emailBind;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.nike_name
	 *
	 * @mbggenerated
	 */
	private String nikeName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.headimg
	 *
	 * @mbggenerated
	 */
	private String headimg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.lastlogin_time
	 *
	 * @mbggenerated
	 */
	private Date lastloginTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.lastlogin_ip
	 *
	 * @mbggenerated
	 */
	private String lastloginIp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.address
	 *
	 * @mbggenerated
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.status
	 *
	 * @mbggenerated
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.isgad
	 *
	 * @mbggenerated
	 */
	private Integer isgad;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.accunt_type
	 *
	 * @mbggenerated
	 */
	private Integer accuntType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.creat_date
	 *
	 * @mbggenerated
	 */
	private Date creatDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.creator
	 *
	 * @mbggenerated
	 */
	private String creator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.modify_date
	 *
	 * @mbggenerated
	 */
	private Date modifyDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.modifier
	 *
	 * @mbggenerated
	 */
	private String modifier;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.fans_num
	 *
	 * @mbggenerated
	 */
	private Integer fansNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.pat_num
	 *
	 * @mbggenerated
	 */
	private Integer patNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.blog_num
	 *
	 * @mbggenerated
	 */
	private Integer blogNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.isrecommend
	 *
	 * @mbggenerated
	 */
	private Integer isrecommend;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.pv_num
	 *
	 * @mbggenerated
	 */
	private Integer pvNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.weight
	 *
	 * @mbggenerated
	 */
	private Integer weight;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.call_history_prod
	 *
	 * @mbggenerated
	 */
	private String callHistoryProd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.call_history_man
	 *
	 * @mbggenerated
	 */
	private String callHistoryMan;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.personal_simple_profile
	 *
	 * @mbggenerated
	 */
	private String personalSimpleProfile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.pwd_level
	 *
	 * @mbggenerated
	 */
	private Integer pwdLevel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.heading_small
	 *
	 * @mbggenerated
	 */
	private String headingSmall;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.tags
	 *
	 * @mbggenerated
	 */
	private String tags;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.active_num
	 *
	 * @mbggenerated
	 */
	private Integer activeNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.liveness
	 *
	 * @mbggenerated
	 */
	private Integer liveness;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.liveness_init
	 *
	 * @mbggenerated
	 */
	private Integer livenessInit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.pv_last_time
	 *
	 * @mbggenerated
	 */
	private Date pvLastTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.ispmcompany
	 *
	 * @mbggenerated
	 */
	private Integer ispmcompany;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.hot_weight
	 *
	 * @mbggenerated
	 */
	private Integer hotWeight;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.isinterest
	 *
	 * @mbggenerated
	 */
	private Integer isinterest;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.isguide
	 *
	 * @mbggenerated
	 */
	private Integer isguide;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.score_result
	 *
	 * @mbggenerated
	 */
	private Integer scoreResult;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.isfundguide
	 *
	 * @mbggenerated
	 */
	private Integer isfundguide;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ism_user.controller_switch
	 *
	 * @mbggenerated
	 */
	private Integer controllerSwitch;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table ism_user
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.user_id
	 *
	 * @return the value of ism_user.user_id
	 *
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.user_id
	 *
	 * @param userId
	 *            the value for ism_user.user_id
	 *
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.user_name
	 *
	 * @return the value of ism_user.user_name
	 *
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.user_name
	 *
	 * @param userName
	 *            the value for ism_user.user_name
	 *
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.password
	 *
	 * @return the value of ism_user.password
	 *
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.password
	 *
	 * @param password
	 *            the value for ism_user.password
	 *
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.sex
	 *
	 * @return the value of ism_user.sex
	 *
	 * @mbggenerated
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.sex
	 *
	 * @param sex
	 *            the value for ism_user.sex
	 *
	 * @mbggenerated
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.register_time
	 *
	 * @return the value of ism_user.register_time
	 *
	 * @mbggenerated
	 */
	public Date getRegisterTime() {
		return registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.register_time
	 *
	 * @param registerTime
	 *            the value for ism_user.register_time
	 *
	 * @mbggenerated
	 */
	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.register_ip
	 *
	 * @return the value of ism_user.register_ip
	 *
	 * @mbggenerated
	 */
	public String getRegisterIp() {
		return registerIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.register_ip
	 *
	 * @param registerIp
	 *            the value for ism_user.register_ip
	 *
	 * @mbggenerated
	 */
	public void setRegisterIp(String registerIp) {
		this.registerIp = registerIp == null ? null : registerIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.mobile
	 *
	 * @return the value of ism_user.mobile
	 *
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.mobile
	 *
	 * @param mobile
	 *            the value for ism_user.mobile
	 *
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.mobile_bind
	 *
	 * @return the value of ism_user.mobile_bind
	 *
	 * @mbggenerated
	 */
	public Integer getMobileBind() {
		return mobileBind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.mobile_bind
	 *
	 * @param mobileBind
	 *            the value for ism_user.mobile_bind
	 *
	 * @mbggenerated
	 */
	public void setMobileBind(Integer mobileBind) {
		this.mobileBind = mobileBind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.email
	 *
	 * @return the value of ism_user.email
	 *
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.email
	 *
	 * @param email
	 *            the value for ism_user.email
	 *
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.email_bind
	 *
	 * @return the value of ism_user.email_bind
	 *
	 * @mbggenerated
	 */
	public Integer getEmailBind() {
		return emailBind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.email_bind
	 *
	 * @param emailBind
	 *            the value for ism_user.email_bind
	 *
	 * @mbggenerated
	 */
	public void setEmailBind(Integer emailBind) {
		this.emailBind = emailBind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.nike_name
	 *
	 * @return the value of ism_user.nike_name
	 *
	 * @mbggenerated
	 */
	public String getNikeName() {
		return nikeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.nike_name
	 *
	 * @param nikeName
	 *            the value for ism_user.nike_name
	 *
	 * @mbggenerated
	 */
	public void setNikeName(String nikeName) {
		this.nikeName = nikeName == null ? null : nikeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.headimg
	 *
	 * @return the value of ism_user.headimg
	 *
	 * @mbggenerated
	 */
	public String getHeadimg() {
		return headimg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.headimg
	 *
	 * @param headimg
	 *            the value for ism_user.headimg
	 *
	 * @mbggenerated
	 */
	public void setHeadimg(String headimg) {
		this.headimg = headimg == null ? null : headimg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.lastlogin_time
	 *
	 * @return the value of ism_user.lastlogin_time
	 *
	 * @mbggenerated
	 */
	public Date getLastloginTime() {
		return lastloginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.lastlogin_time
	 *
	 * @param lastloginTime
	 *            the value for ism_user.lastlogin_time
	 *
	 * @mbggenerated
	 */
	public void setLastloginTime(Date lastloginTime) {
		this.lastloginTime = lastloginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.lastlogin_ip
	 *
	 * @return the value of ism_user.lastlogin_ip
	 *
	 * @mbggenerated
	 */
	public String getLastloginIp() {
		return lastloginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.lastlogin_ip
	 *
	 * @param lastloginIp
	 *            the value for ism_user.lastlogin_ip
	 *
	 * @mbggenerated
	 */
	public void setLastloginIp(String lastloginIp) {
		this.lastloginIp = lastloginIp == null ? null : lastloginIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.address
	 *
	 * @return the value of ism_user.address
	 *
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.address
	 *
	 * @param address
	 *            the value for ism_user.address
	 *
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.status
	 *
	 * @return the value of ism_user.status
	 *
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.status
	 *
	 * @param status
	 *            the value for ism_user.status
	 *
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.isgad
	 *
	 * @return the value of ism_user.isgad
	 *
	 * @mbggenerated
	 */
	public Integer getIsgad() {
		return isgad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.isgad
	 *
	 * @param isgad
	 *            the value for ism_user.isgad
	 *
	 * @mbggenerated
	 */
	public void setIsgad(Integer isgad) {
		this.isgad = isgad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.accunt_type
	 *
	 * @return the value of ism_user.accunt_type
	 *
	 * @mbggenerated
	 */
	public Integer getAccuntType() {
		return accuntType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.accunt_type
	 *
	 * @param accuntType
	 *            the value for ism_user.accunt_type
	 *
	 * @mbggenerated
	 */
	public void setAccuntType(Integer accuntType) {
		this.accuntType = accuntType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.creat_date
	 *
	 * @return the value of ism_user.creat_date
	 *
	 * @mbggenerated
	 */
	public Date getCreatDate() {
		return creatDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.creat_date
	 *
	 * @param creatDate
	 *            the value for ism_user.creat_date
	 *
	 * @mbggenerated
	 */
	public void setCreatDate(Date creatDate) {
		this.creatDate = creatDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.creator
	 *
	 * @return the value of ism_user.creator
	 *
	 * @mbggenerated
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.creator
	 *
	 * @param creator
	 *            the value for ism_user.creator
	 *
	 * @mbggenerated
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.modify_date
	 *
	 * @return the value of ism_user.modify_date
	 *
	 * @mbggenerated
	 */
	public Date getModifyDate() {
		return modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.modify_date
	 *
	 * @param modifyDate
	 *            the value for ism_user.modify_date
	 *
	 * @mbggenerated
	 */
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.modifier
	 *
	 * @return the value of ism_user.modifier
	 *
	 * @mbggenerated
	 */
	public String getModifier() {
		return modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.modifier
	 *
	 * @param modifier
	 *            the value for ism_user.modifier
	 *
	 * @mbggenerated
	 */
	public void setModifier(String modifier) {
		this.modifier = modifier == null ? null : modifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.fans_num
	 *
	 * @return the value of ism_user.fans_num
	 *
	 * @mbggenerated
	 */
	public Integer getFansNum() {
		return fansNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.fans_num
	 *
	 * @param fansNum
	 *            the value for ism_user.fans_num
	 *
	 * @mbggenerated
	 */
	public void setFansNum(Integer fansNum) {
		this.fansNum = fansNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.pat_num
	 *
	 * @return the value of ism_user.pat_num
	 *
	 * @mbggenerated
	 */
	public Integer getPatNum() {
		return patNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.pat_num
	 *
	 * @param patNum
	 *            the value for ism_user.pat_num
	 *
	 * @mbggenerated
	 */
	public void setPatNum(Integer patNum) {
		this.patNum = patNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.blog_num
	 *
	 * @return the value of ism_user.blog_num
	 *
	 * @mbggenerated
	 */
	public Integer getBlogNum() {
		return blogNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.blog_num
	 *
	 * @param blogNum
	 *            the value for ism_user.blog_num
	 *
	 * @mbggenerated
	 */
	public void setBlogNum(Integer blogNum) {
		this.blogNum = blogNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.isrecommend
	 *
	 * @return the value of ism_user.isrecommend
	 *
	 * @mbggenerated
	 */
	public Integer getIsrecommend() {
		return isrecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.isrecommend
	 *
	 * @param isrecommend
	 *            the value for ism_user.isrecommend
	 *
	 * @mbggenerated
	 */
	public void setIsrecommend(Integer isrecommend) {
		this.isrecommend = isrecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.pv_num
	 *
	 * @return the value of ism_user.pv_num
	 *
	 * @mbggenerated
	 */
	public Integer getPvNum() {
		return pvNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.pv_num
	 *
	 * @param pvNum
	 *            the value for ism_user.pv_num
	 *
	 * @mbggenerated
	 */
	public void setPvNum(Integer pvNum) {
		this.pvNum = pvNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.weight
	 *
	 * @return the value of ism_user.weight
	 *
	 * @mbggenerated
	 */
	public Integer getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.weight
	 *
	 * @param weight
	 *            the value for ism_user.weight
	 *
	 * @mbggenerated
	 */
	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.call_history_prod
	 *
	 * @return the value of ism_user.call_history_prod
	 *
	 * @mbggenerated
	 */
	public String getCallHistoryProd() {
		return callHistoryProd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.call_history_prod
	 *
	 * @param callHistoryProd
	 *            the value for ism_user.call_history_prod
	 *
	 * @mbggenerated
	 */
	public void setCallHistoryProd(String callHistoryProd) {
		this.callHistoryProd = callHistoryProd == null ? null : callHistoryProd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.call_history_man
	 *
	 * @return the value of ism_user.call_history_man
	 *
	 * @mbggenerated
	 */
	public String getCallHistoryMan() {
		return callHistoryMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.call_history_man
	 *
	 * @param callHistoryMan
	 *            the value for ism_user.call_history_man
	 *
	 * @mbggenerated
	 */
	public void setCallHistoryMan(String callHistoryMan) {
		this.callHistoryMan = callHistoryMan == null ? null : callHistoryMan.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.personal_simple_profile
	 *
	 * @return the value of ism_user.personal_simple_profile
	 *
	 * @mbggenerated
	 */
	public String getPersonalSimpleProfile() {
		return personalSimpleProfile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.personal_simple_profile
	 *
	 * @param personalSimpleProfile
	 *            the value for ism_user.personal_simple_profile
	 *
	 * @mbggenerated
	 */
	public void setPersonalSimpleProfile(String personalSimpleProfile) {
		this.personalSimpleProfile = personalSimpleProfile == null ? null : personalSimpleProfile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.pwd_level
	 *
	 * @return the value of ism_user.pwd_level
	 *
	 * @mbggenerated
	 */
	public Integer getPwdLevel() {
		return pwdLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.pwd_level
	 *
	 * @param pwdLevel
	 *            the value for ism_user.pwd_level
	 *
	 * @mbggenerated
	 */
	public void setPwdLevel(Integer pwdLevel) {
		this.pwdLevel = pwdLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.heading_small
	 *
	 * @return the value of ism_user.heading_small
	 *
	 * @mbggenerated
	 */
	public String getHeadingSmall() {
		return headingSmall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.heading_small
	 *
	 * @param headingSmall
	 *            the value for ism_user.heading_small
	 *
	 * @mbggenerated
	 */
	public void setHeadingSmall(String headingSmall) {
		this.headingSmall = headingSmall == null ? null : headingSmall.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.tags
	 *
	 * @return the value of ism_user.tags
	 *
	 * @mbggenerated
	 */
	public String getTags() {
		return tags;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.tags
	 *
	 * @param tags
	 *            the value for ism_user.tags
	 *
	 * @mbggenerated
	 */
	public void setTags(String tags) {
		this.tags = tags == null ? null : tags.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.active_num
	 *
	 * @return the value of ism_user.active_num
	 *
	 * @mbggenerated
	 */
	public Integer getActiveNum() {
		return activeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.active_num
	 *
	 * @param activeNum
	 *            the value for ism_user.active_num
	 *
	 * @mbggenerated
	 */
	public void setActiveNum(Integer activeNum) {
		this.activeNum = activeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.liveness
	 *
	 * @return the value of ism_user.liveness
	 *
	 * @mbggenerated
	 */
	public Integer getLiveness() {
		return liveness;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.liveness
	 *
	 * @param liveness
	 *            the value for ism_user.liveness
	 *
	 * @mbggenerated
	 */
	public void setLiveness(Integer liveness) {
		this.liveness = liveness;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.liveness_init
	 *
	 * @return the value of ism_user.liveness_init
	 *
	 * @mbggenerated
	 */
	public Integer getLivenessInit() {
		return livenessInit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.liveness_init
	 *
	 * @param livenessInit
	 *            the value for ism_user.liveness_init
	 *
	 * @mbggenerated
	 */
	public void setLivenessInit(Integer livenessInit) {
		this.livenessInit = livenessInit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.pv_last_time
	 *
	 * @return the value of ism_user.pv_last_time
	 *
	 * @mbggenerated
	 */
	public Date getPvLastTime() {
		return pvLastTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.pv_last_time
	 *
	 * @param pvLastTime
	 *            the value for ism_user.pv_last_time
	 *
	 * @mbggenerated
	 */
	public void setPvLastTime(Date pvLastTime) {
		this.pvLastTime = pvLastTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.ispmcompany
	 *
	 * @return the value of ism_user.ispmcompany
	 *
	 * @mbggenerated
	 */
	public Integer getIspmcompany() {
		return ispmcompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.ispmcompany
	 *
	 * @param ispmcompany
	 *            the value for ism_user.ispmcompany
	 *
	 * @mbggenerated
	 */
	public void setIspmcompany(Integer ispmcompany) {
		this.ispmcompany = ispmcompany;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.hot_weight
	 *
	 * @return the value of ism_user.hot_weight
	 *
	 * @mbggenerated
	 */
	public Integer getHotWeight() {
		return hotWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.hot_weight
	 *
	 * @param hotWeight
	 *            the value for ism_user.hot_weight
	 *
	 * @mbggenerated
	 */
	public void setHotWeight(Integer hotWeight) {
		this.hotWeight = hotWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.isinterest
	 *
	 * @return the value of ism_user.isinterest
	 *
	 * @mbggenerated
	 */
	public Integer getIsinterest() {
		return isinterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.isinterest
	 *
	 * @param isinterest
	 *            the value for ism_user.isinterest
	 *
	 * @mbggenerated
	 */
	public void setIsinterest(Integer isinterest) {
		this.isinterest = isinterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.isguide
	 *
	 * @return the value of ism_user.isguide
	 *
	 * @mbggenerated
	 */
	public Integer getIsguide() {
		return isguide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.isguide
	 *
	 * @param isguide
	 *            the value for ism_user.isguide
	 *
	 * @mbggenerated
	 */
	public void setIsguide(Integer isguide) {
		this.isguide = isguide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.score_result
	 *
	 * @return the value of ism_user.score_result
	 *
	 * @mbggenerated
	 */
	public Integer getScoreResult() {
		return scoreResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.score_result
	 *
	 * @param scoreResult
	 *            the value for ism_user.score_result
	 *
	 * @mbggenerated
	 */
	public void setScoreResult(Integer scoreResult) {
		this.scoreResult = scoreResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.isfundguide
	 *
	 * @return the value of ism_user.isfundguide
	 *
	 * @mbggenerated
	 */
	public Integer getIsfundguide() {
		return isfundguide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.isfundguide
	 *
	 * @param isfundguide
	 *            the value for ism_user.isfundguide
	 *
	 * @mbggenerated
	 */
	public void setIsfundguide(Integer isfundguide) {
		this.isfundguide = isfundguide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ism_user.controller_switch
	 *
	 * @return the value of ism_user.controller_switch
	 *
	 * @mbggenerated
	 */
	public Integer getControllerSwitch() {
		return controllerSwitch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ism_user.controller_switch
	 *
	 * @param controllerSwitch
	 *            the value for ism_user.controller_switch
	 *
	 * @mbggenerated
	 */
	public void setControllerSwitch(Integer controllerSwitch) {
		this.controllerSwitch = controllerSwitch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UserIsmBean other = (UserIsmBean) that;
		return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
				&& (this.getUserName() == null ? other.getUserName() == null
						: this.getUserName().equals(other.getUserName()))
				&& (this.getPassword() == null ? other.getPassword() == null
						: this.getPassword().equals(other.getPassword()))
				&& (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
				&& (this.getRegisterTime() == null ? other.getRegisterTime() == null
						: this.getRegisterTime().equals(other.getRegisterTime()))
				&& (this.getRegisterIp() == null ? other.getRegisterIp() == null
						: this.getRegisterIp().equals(other.getRegisterIp()))
				&& (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
				&& (this.getMobileBind() == null ? other.getMobileBind() == null
						: this.getMobileBind().equals(other.getMobileBind()))
				&& (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
				&& (this.getEmailBind() == null ? other.getEmailBind() == null
						: this.getEmailBind().equals(other.getEmailBind()))
				&& (this.getNikeName() == null ? other.getNikeName() == null
						: this.getNikeName().equals(other.getNikeName()))
				&& (this.getHeadimg() == null ? other.getHeadimg() == null
						: this.getHeadimg().equals(other.getHeadimg()))
				&& (this.getLastloginTime() == null ? other.getLastloginTime() == null
						: this.getLastloginTime().equals(other.getLastloginTime()))
				&& (this.getLastloginIp() == null ? other.getLastloginIp() == null
						: this.getLastloginIp().equals(other.getLastloginIp()))
				&& (this.getAddress() == null ? other.getAddress() == null
						: this.getAddress().equals(other.getAddress()))
				&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
				&& (this.getIsgad() == null ? other.getIsgad() == null : this.getIsgad().equals(other.getIsgad()))
				&& (this.getAccuntType() == null ? other.getAccuntType() == null
						: this.getAccuntType().equals(other.getAccuntType()))
				&& (this.getCreatDate() == null ? other.getCreatDate() == null
						: this.getCreatDate().equals(other.getCreatDate()))
				&& (this.getCreator() == null ? other.getCreator() == null
						: this.getCreator().equals(other.getCreator()))
				&& (this.getModifyDate() == null ? other.getModifyDate() == null
						: this.getModifyDate().equals(other.getModifyDate()))
				&& (this.getModifier() == null ? other.getModifier() == null
						: this.getModifier().equals(other.getModifier()))
				&& (this.getFansNum() == null ? other.getFansNum() == null
						: this.getFansNum().equals(other.getFansNum()))
				&& (this.getPatNum() == null ? other.getPatNum() == null : this.getPatNum().equals(other.getPatNum()))
				&& (this.getBlogNum() == null ? other.getBlogNum() == null
						: this.getBlogNum().equals(other.getBlogNum()))
				&& (this.getIsrecommend() == null ? other.getIsrecommend() == null
						: this.getIsrecommend().equals(other.getIsrecommend()))
				&& (this.getPvNum() == null ? other.getPvNum() == null : this.getPvNum().equals(other.getPvNum()))
				&& (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
				&& (this.getCallHistoryProd() == null ? other.getCallHistoryProd() == null
						: this.getCallHistoryProd().equals(other.getCallHistoryProd()))
				&& (this.getCallHistoryMan() == null ? other.getCallHistoryMan() == null
						: this.getCallHistoryMan().equals(other.getCallHistoryMan()))
				&& (this.getPersonalSimpleProfile() == null ? other.getPersonalSimpleProfile() == null
						: this.getPersonalSimpleProfile().equals(other.getPersonalSimpleProfile()))
				&& (this.getPwdLevel() == null ? other.getPwdLevel() == null
						: this.getPwdLevel().equals(other.getPwdLevel()))
				&& (this.getHeadingSmall() == null ? other.getHeadingSmall() == null
						: this.getHeadingSmall().equals(other.getHeadingSmall()))
				&& (this.getTags() == null ? other.getTags() == null : this.getTags().equals(other.getTags()))
				&& (this.getActiveNum() == null ? other.getActiveNum() == null
						: this.getActiveNum().equals(other.getActiveNum()))
				&& (this.getLiveness() == null ? other.getLiveness() == null
						: this.getLiveness().equals(other.getLiveness()))
				&& (this.getLivenessInit() == null ? other.getLivenessInit() == null
						: this.getLivenessInit().equals(other.getLivenessInit()))
				&& (this.getPvLastTime() == null ? other.getPvLastTime() == null
						: this.getPvLastTime().equals(other.getPvLastTime()))
				&& (this.getIspmcompany() == null ? other.getIspmcompany() == null
						: this.getIspmcompany().equals(other.getIspmcompany()))
				&& (this.getHotWeight() == null ? other.getHotWeight() == null
						: this.getHotWeight().equals(other.getHotWeight()))
				&& (this.getIsinterest() == null ? other.getIsinterest() == null
						: this.getIsinterest().equals(other.getIsinterest()))
				&& (this.getIsguide() == null ? other.getIsguide() == null
						: this.getIsguide().equals(other.getIsguide()))
				&& (this.getScoreResult() == null ? other.getScoreResult() == null
						: this.getScoreResult().equals(other.getScoreResult()))
				&& (this.getIsfundguide() == null ? other.getIsfundguide() == null
						: this.getIsfundguide().equals(other.getIsfundguide()))
				&& (this.getControllerSwitch() == null ? other.getControllerSwitch() == null
						: this.getControllerSwitch().equals(other.getControllerSwitch()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
		result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
		result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
		result = prime * result + ((getRegisterTime() == null) ? 0 : getRegisterTime().hashCode());
		result = prime * result + ((getRegisterIp() == null) ? 0 : getRegisterIp().hashCode());
		result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
		result = prime * result + ((getMobileBind() == null) ? 0 : getMobileBind().hashCode());
		result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
		result = prime * result + ((getEmailBind() == null) ? 0 : getEmailBind().hashCode());
		result = prime * result + ((getNikeName() == null) ? 0 : getNikeName().hashCode());
		result = prime * result + ((getHeadimg() == null) ? 0 : getHeadimg().hashCode());
		result = prime * result + ((getLastloginTime() == null) ? 0 : getLastloginTime().hashCode());
		result = prime * result + ((getLastloginIp() == null) ? 0 : getLastloginIp().hashCode());
		result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getIsgad() == null) ? 0 : getIsgad().hashCode());
		result = prime * result + ((getAccuntType() == null) ? 0 : getAccuntType().hashCode());
		result = prime * result + ((getCreatDate() == null) ? 0 : getCreatDate().hashCode());
		result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
		result = prime * result + ((getModifyDate() == null) ? 0 : getModifyDate().hashCode());
		result = prime * result + ((getModifier() == null) ? 0 : getModifier().hashCode());
		result = prime * result + ((getFansNum() == null) ? 0 : getFansNum().hashCode());
		result = prime * result + ((getPatNum() == null) ? 0 : getPatNum().hashCode());
		result = prime * result + ((getBlogNum() == null) ? 0 : getBlogNum().hashCode());
		result = prime * result + ((getIsrecommend() == null) ? 0 : getIsrecommend().hashCode());
		result = prime * result + ((getPvNum() == null) ? 0 : getPvNum().hashCode());
		result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
		result = prime * result + ((getCallHistoryProd() == null) ? 0 : getCallHistoryProd().hashCode());
		result = prime * result + ((getCallHistoryMan() == null) ? 0 : getCallHistoryMan().hashCode());
		result = prime * result + ((getPersonalSimpleProfile() == null) ? 0 : getPersonalSimpleProfile().hashCode());
		result = prime * result + ((getPwdLevel() == null) ? 0 : getPwdLevel().hashCode());
		result = prime * result + ((getHeadingSmall() == null) ? 0 : getHeadingSmall().hashCode());
		result = prime * result + ((getTags() == null) ? 0 : getTags().hashCode());
		result = prime * result + ((getActiveNum() == null) ? 0 : getActiveNum().hashCode());
		result = prime * result + ((getLiveness() == null) ? 0 : getLiveness().hashCode());
		result = prime * result + ((getLivenessInit() == null) ? 0 : getLivenessInit().hashCode());
		result = prime * result + ((getPvLastTime() == null) ? 0 : getPvLastTime().hashCode());
		result = prime * result + ((getIspmcompany() == null) ? 0 : getIspmcompany().hashCode());
		result = prime * result + ((getHotWeight() == null) ? 0 : getHotWeight().hashCode());
		result = prime * result + ((getIsinterest() == null) ? 0 : getIsinterest().hashCode());
		result = prime * result + ((getIsguide() == null) ? 0 : getIsguide().hashCode());
		result = prime * result + ((getScoreResult() == null) ? 0 : getScoreResult().hashCode());
		result = prime * result + ((getIsfundguide() == null) ? 0 : getIsfundguide().hashCode());
		result = prime * result + ((getControllerSwitch() == null) ? 0 : getControllerSwitch().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ism_user
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", userId=").append(userId);
		sb.append(", userName=").append(userName);
		sb.append(", password=").append(password);
		sb.append(", sex=").append(sex);
		sb.append(", registerTime=").append(registerTime);
		sb.append(", registerIp=").append(registerIp);
		sb.append(", mobile=").append(mobile);
		sb.append(", mobileBind=").append(mobileBind);
		sb.append(", email=").append(email);
		sb.append(", emailBind=").append(emailBind);
		sb.append(", nikeName=").append(nikeName);
		sb.append(", headimg=").append(headimg);
		sb.append(", lastloginTime=").append(lastloginTime);
		sb.append(", lastloginIp=").append(lastloginIp);
		sb.append(", address=").append(address);
		sb.append(", status=").append(status);
		sb.append(", isgad=").append(isgad);
		sb.append(", accuntType=").append(accuntType);
		sb.append(", creatDate=").append(creatDate);
		sb.append(", creator=").append(creator);
		sb.append(", modifyDate=").append(modifyDate);
		sb.append(", modifier=").append(modifier);
		sb.append(", fansNum=").append(fansNum);
		sb.append(", patNum=").append(patNum);
		sb.append(", blogNum=").append(blogNum);
		sb.append(", isrecommend=").append(isrecommend);
		sb.append(", pvNum=").append(pvNum);
		sb.append(", weight=").append(weight);
		sb.append(", callHistoryProd=").append(callHistoryProd);
		sb.append(", callHistoryMan=").append(callHistoryMan);
		sb.append(", personalSimpleProfile=").append(personalSimpleProfile);
		sb.append(", pwdLevel=").append(pwdLevel);
		sb.append(", headingSmall=").append(headingSmall);
		sb.append(", tags=").append(tags);
		sb.append(", activeNum=").append(activeNum);
		sb.append(", liveness=").append(liveness);
		sb.append(", livenessInit=").append(livenessInit);
		sb.append(", pvLastTime=").append(pvLastTime);
		sb.append(", ispmcompany=").append(ispmcompany);
		sb.append(", hotWeight=").append(hotWeight);
		sb.append(", isinterest=").append(isinterest);
		sb.append(", isguide=").append(isguide);
		sb.append(", scoreResult=").append(scoreResult);
		sb.append(", isfundguide=").append(isfundguide);
		sb.append(", controllerSwitch=").append(controllerSwitch);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}
